spring:
  application:
    name: data-integration-api
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  datasource:
    url: ${DATA_INTEGRATION_API_DB_URL}
    username: ${DATA_INTEGRATION_API_DB_USERNAME}
    password: ${DATA_INTEGRATION_API_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${DATA_INTEGRATION_API_REDIS_HOST}
      port: ${DATA_INTEGRATION_API_REDIS_PORT}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
  rabbitmq:
    host: ${DATA_INTEGRATION_API_QUEUEMGR_HOST}
    port: ${DATA_INTEGRATION_API_QUEUEMGR_PORT}
    username: ${DATA_INTEGRATION_API_QUEUEMGR_USERNAME}
    password: ${DATA_INTEGRATION_API_QUEUEMGR_PASSWORD}
info:
  app:
    name: data-integration-api

server:
  port: 8085

logging:
  level:
    root: INFO

service:
  token-path: ${KEYCLOAK_TOKEN_PATH}
  company:
    client-id: ${MDM_COMPANY_CONVERSION_API_CLIENT_ID}
    client-secret: ${MDM_COMPANY_CONVERSION_API_CLIENT_SECRET}
    host: ${MDM_COMPANY_CONVERSION_API_HOST}
  person:
    client-id: ${MDM_PERSON_CONVERSION_API_CLIENT_ID}
    client-secret: ${MDM_PERSON_CONVERSION_API_CLIENT_SECRET}
    host: ${MDM_PERSON_CONVERSION_API_HOST}
  acl:
    client-id: ${DATA_INTEGRATION_ACL_API_CLIENT_ID}
    client-secret: ${DATA_INTEGRATION_ACL_API_CLIENT_SECRET}
    host: ${DATA_INTEGRATION_ACL_API_HOST}
