spring:
  application:
    name: data-integration-api
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://localhost:5432/dataintegration
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
#    url: jdbc:h2:file:/data/demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;MODE=PostgreSQL;
#    username: sa
#    driver-class-name: org.h2.Driver
#    password: password
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        trace: false
#        web-allow-others: false
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/data-integration-realm
  rabbitmq:
    host: localhost
    port: 5672
    username: data-integration-adm
    password: data-integration-adm
info:
  app:
    name: data-integration-api

server:
  port: 8085

logging:
  level:
    root: INFO

service:
  token-path: http://localhost:8080/realms/data-integration-realm/protocol/openid-connect/token
  company:
    client-id: mdm-company-conversion-api
    client-secret: weCV7dPMZWRDkSZ4w5hrgVt2iV3epXUJ
    host: http://localhost:8081/api/company
  person:
    client-id: mdm-person-conversion-api
    client-secret: qQugVPu7CoCKeOnVLR22OEX7ErYjS7J7
    host: http://localhost:8082/api/person
  acl:
    client-id: data-integration-to-legacy-acl-api
    client-secret: r17VYLAiUHmfrnXuQlmwL3RyMeFyuuX6
    host: http://localhost:8083/api
